# Project: œÓƒø2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = c”Ô—‘_private.res
OBJ      = main.o test.o $(RES)
LINKOBJ  = main.o test.o $(RES)
LIBS     = -L"C:/App/DevC++/Dev-Cpp/MinGW64/lib" -L"C:/App/DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/App/DevC++/Dev-Cpp/MinGW64/include" -I"C:/App/DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/App/DevC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/App/DevC++/Dev-Cpp/MinGW64/include" -I"C:/App/DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/App/DevC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/App/DevC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = c”Ô—‘.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CC) -c main.cpp -o main.o $(CFLAGS)

test.o: test.c
	$(CC) -c test.c -o test.o $(CFLAGS)

c”Ô—‘_private.res: c”Ô—‘_private.rc 
	$(WINDRES) -i c”Ô—‘_private.rc --input-format=rc -o c”Ô—‘_private.res -O coff 

